baseURL = "https://mohamissa.github.io/hamissa-blog/"
languageCode = "en-us"
title = "Hamissa's Technial Blog"
theme = "m10c"

[params]
  author = "Mohammed Hamissa"
  description = "a Technical Showcase| I hope you like it!!"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/mohamissa"
